<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="ADMINRG-MKE61HL" ignored="3" name="PersonalLoan" tests="4" failures="1" timestamp="13 Aug 2020 12:00:18 GMT" time="0.099" errors="0">
  <testcase name="mobileLoginHomeLoan" time="0.005" classname="TestNg_Tutorial.Test4"/>
  <testcase name="Third" time="0.011" classname="TestNg_Tutorial.Test2"/>
  <testcase name="demo" time="0.013" classname="TestNg_Tutorial.Test1"/>
  <testcase name="secondMethod" time="0.007" classname="TestNg_Tutorial.Test1">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at TestNg_Tutorial.Test1.secondMethod(Test1.java:51)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- secondMethod -->
  <testcase name="loginAPIHomeLoan" time="0.0" classname="TestNg_Tutorial.Test4">
    <ignored/>
  </testcase> <!-- loginAPIHomeLoan -->
  <testcase name="webLoginHomeLoan" time="0.0" classname="TestNg_Tutorial.Test4">
    <ignored/>
  </testcase> <!-- webLoginHomeLoan -->
  <testcase name="zMethod" time="0.0" classname="TestNg_Tutorial.Test1">
    <ignored/>
  </testcase> <!-- zMethod -->
</testsuite> <!-- PersonalLoan -->
